image: alpine/edge
packages:
  - sudo
  - npm
sources:
  - https://git.sr.ht/~postmarketos/pmbootstrap
tasks:
  - note: |
      pmbootstrap/.ci/note.sh
  - shellcheck: |
      cd pmbootstrap
      sudo .ci/shellcheck.sh
  - ruff: |
      cd pmbootstrap
      sudo .ci/ruff.sh
  - vermin: |
      cd pmbootstrap
      sudo .ci/vermin.sh
  - codespell: |
      cd pmbootstrap
      sudo .ci/codespell.sh
  - pytest: |
      cd pmbootstrap
      sudo .ci/pytest.sh
  - markdownlint: |
      cd pmbootstrap
      sudo .ci/markdownlint.sh
artifacts:
  - ".local/var/pmbootstrap/log.txt"
  - ".local/var/pmbootstrap/log_testsuite.txt"
