image: alpine/edge
packages:
  - sudo
sources:
  - https://git.sr.ht/~postmarketos/pmbootstrap
tasks:
  - pytest: |
      cd pmbootstrap
      sudo .ci/pytest.sh
artifacts:
  - ".local/var/pmbootstrap/log.txt"
  - ".local/var/pmbootstrap/log_testsuite.txt"
